import assert from 'node:assert/strict';
import test from 'node:test';
import { buildPlanPayload, buildUserPayload, canManage, planPeriodEligibility, queryPath, userTerminals, validatedItems, validatedPlanPreview } from './management-data.js';

test('management scope follows assigned terminals and roles', () => {
  assert.deepEqual(userTerminals({ role: 'admin', terminals: ['cua_lo'] }), ['cua_lo']);
  assert.deepEqual(userTerminals({ terminals: ['unknown'] }), []);
  assert.equal(canManage({ role: 'viewer' }), false);
  assert.equal(canManage({ role: 'manager' }), true);
});

test('monthly plan comparison accepts any valid end date in a period beginning on the first day', () => {
  assert.equal(planPeriodEligibility({ start_date: '2026-09-01', end_date: '2026-09-13' }, '2026-09-13').eligible, true);
  assert.equal(planPeriodEligibility({ start_date: '2026-08-01', end_date: '2026-08-31' }, '2026-09-13').eligible, true);
  assert.equal(planPeriodEligibility({ start_date: '2028-02-01', end_date: '2028-02-29' }, '2028-03-01').eligible, true);
  assert.equal(planPeriodEligibility({ start_date: '2026-09-01', end_date: '2026-09-12' }, '2026-09-13').eligible, true);
  assert.equal(planPeriodEligibility({ start_date: '2026-08-01', end_date: '2026-08-05' }, '2026-09-13').eligible, true);
  assert.equal(planPeriodEligibility({ start_date: '2026-09-01', end_date: '2026-09-01' }).eligible, true);
  for (const filters of [
    { start_date: '2026-09-02', end_date: '2026-09-13' },
    { start_date: '2026-08-01', end_date: '2026-09-13' },
    { start_date: '2026-09-01', end_date: '2026-08-31' },
    { start_date: '2026-09-01', end_date: '2026-09-31' },
    { start_date: '2026-02-01', end_date: '2026-02-29' },
    { start_date: '2026-09-01', end_date: '' },
  ]) assert.equal(planPeriodEligibility(filters, '2026-09-13').eligible, false);
});

test('plans require an authorized terminal, approved-document reference and explicit nonnegative amount', () => {
  const form = { terminal: 'cua_lo', period_type: 'month', month: '2026-09', metric: 'tonnage', amount: '0', reference: ' KH-09 ', note: '' };
  assert.equal(buildPlanPayload(form, ['cua_lo']).amount, 0);
  assert.equal(buildPlanPayload(form, ['cua_lo']).reference, 'KH-09');
  for (const change of [{ terminal: 'ben_thuy' }, { amount: '' }, { amount: '-1' }, { amount: 'NaN' }, { amount: 'Infinity' }, { month: '2026-13' }, { month: '2100-01' }, { reference: ' ' }]) {
    assert.throws(() => buildPlanPayload({ ...form, ...change }, ['cua_lo']));
  }
  const voyage = buildPlanPayload({ ...form, period_type: 'voyage', voyage_id: '101' }, ['cua_lo']);
  assert.equal(voyage.voyage_id, 101);
  assert.equal(voyage.month, undefined);
  assert.throws(() => buildPlanPayload({ ...form, period_type: 'voyage', voyage_id: '2147483648' }, ['cua_lo']));
});

test('new users need an explicit role and terminal scope; passwords are generated by the server', () => {
  const form = { username: 'operator.1', display_name: 'Người dùng', role: 'viewer', terminals: ['cua_lo', 'unknown'], password: 'ignored' };
  assert.deepEqual(buildUserPayload(form), { username: 'operator.1', display_name: 'Người dùng', role: 'viewer', terminals: ['cua_lo'] });
  for (const change of [{ username: 'a' }, { display_name: '' }, { display_name: 'a'.repeat(161) }, { role: 'owner' }, { terminals: [] }]) assert.throws(() => buildUserPayload({ ...form, ...change }));
});

test('list contracts fail visibly and query parameters retain scope safely', () => {
  assert.throws(() => validatedItems({ rows: [] }));
  assert.deepEqual(validatedItems({ items: [] }), []);
  assert.equal(queryPath('/issues', { terminal: 'cua_lo', source_id: 'a&b', page: 1, empty: '' }), '/issues?terminal=cua_lo&source_id=a%26b&page=1');
});

test('Excel confirmation requires a valid preview and every row stays within assigned scope', () => {
  const row = { terminal: 'cua_lo', period_type: 'month', month: '2026-09', metric: 'tonnage', amount: 12.5, reference: 'KH-09' };
  assert.equal(validatedPlanPreview({ valid: true, rows: [row], errors: [] }, ['cua_lo']).rows[0].amount, 12.5);
  for (const preview of [
    { valid: true, rows: [], errors: [] },
    { valid: true, rows: [row], errors: [{ row: 2, message: 'Lỗi' }] },
    { valid: true, rows: [{ ...row, terminal: 'ben_thuy' }], errors: [] },
    { valid: true, rows: [{ ...row, amount: -1 }], errors: [] },
  ]) assert.throws(() => validatedPlanPreview(preview, ['cua_lo']));
});
